
services:
###> doctrine/doctrine-bundle ###
  database:
    image: 'mariadb:${DB_VERSION:-10.11.2}'
    container_name: dynf_database
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_DATABASE: ${DB_NAME:-main}
    ports:
      - '3356:3306'
    volumes:
      - database:/var/lib/mysql
###< doctrine/doctrine-bundle ###

  adminer:
    image: 'adminer:latest'
    container_name: dynf_dbadmin
    depends_on:
      - database
    restart: always
    ports:
      - 8080:8080

volumes:
###> doctrine/doctrine-bundle ###
  database:
###< doctrine/doctrine-bundle ###
